include:
  - project: 'aicactus/common/ci'
    file: '/gitlab-ci/workflow.yaml'
  - project: 'aicactus/common/ci'
    file: '/gitlab-ci/label.yaml'
  - project: 'aicactus/common/ci'
    file: '/gitlab-ci/build.yaml'
  - project: 'aicactus/common/ci'
    file: '/gitlab-ci/deploy.yaml'

stages:
  - label
  - build
  - deploy

Build:
  extends: .build-kaniko
  before_script:
  - |-
    export KANIKO_ARG="$KANIKO_ARG --destination asia-docker.pkg.dev/aicactus-prod/container/adnetwork/portal"
  variables:
    IMAGE_NAME: asia.gcr.io/aicactus-prod/adnetwork/portal

Deploy to staging:
  extends: .deploy-staging
