include:
  - project: 'aicactus/common/ci'
    file: '/gitlab-ci/workflow.yaml'
  - project: 'aicactus/common/ci'
    file: '/gitlab-ci/label.yaml'
  - project: 'aicactus/common/ci'
    file: '/gitlab-ci/build.yaml'
  - project: 'aicactus/common/ci'
    file: '/gitlab-ci/deploy.yaml'

stages:
  - label
  - build
  - push-image
  - deploy

Build:
  extends: .build

Push images to registry:
  extends: .push

Deploy to staging:
  extends: .deploy-staging
