export const HASH_PATH = '#';

export const RoutePaths = {
  LOGIN: 'login',
  REGISTER: 'register',
  DASHBOARD: 'dashboard',
  AUDIENCE: 'audience',
  CREATIVE: 'creative',
  CAMPAIGN: 'campaign',
  STRATEGY: 'strategy',
  INVENTORY_MARKET: 'inventory-market',
  CONTAINER: 'container',
  ORGANIZATION: 'organization',
  PUBLISHER: 'publisher',
  ADVERTISER: 'advertiser',
  DSP: 'dsp',
  USER: 'user',
  PROFILE: 'profile',
  CREATE: 'create',
  EDIT: 'edit',
  REPORT: 'report',
  INVENTORY: 'inventory',
  PAGE: 'page',
  SETTING: 'setting',
  TRACKER: 'tracker',
  POSITION: 'position',
  KEYWORD: 'keyword',
  DOMAIN_GROUP: 'domain-group',
  DOMAIN: 'domain'
};
