export const GET_INVENTORIES = 'GET_INVENTORIES';
export const GET_INVENTORY = 'GET_INVENTORY';
export const GET_INVENTORY_DEAL = 'GET_INVENTORY_DEAL';
export const GET_INVENTORY_BID = 'GET_INVENTORY_BID';
export const GET_INVENTORY_BY_PAGE = 'GET_INVENTORY_BY_PAGE';
