export const GET_AUDIENCES = 'GET_AUDIENCES';
export const GET_AUDIENCE = 'GET_AUDIENCE';
export const AUDIENCES_INFINITY_SIDEBAR = 'AUDIENCES_INFINITY_SIDEBAR';
export const AUDIENCES_INFINITY = 'AUDIENCES_INFINITY';
